//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_store
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PC_storeContext1 : DbContext
    {
        public PC_storeContext1()
            : base("name=PC_storeContext1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Акции> Акции { get; set; }
        public virtual DbSet<БазаКлиентов> БазаКлиентов { get; set; }
        public virtual DbSet<Должности> Должности { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<Объекты> Объекты { get; set; }
        public virtual DbSet<Операции> Операции { get; set; }
        public virtual DbSet<Продукт> Продукт { get; set; }
        public virtual DbSet<Продукты> Продукты { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<Пароли> Пароли { get; set; }
    }
}
