//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_store.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.Операции = new HashSet<Операции>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Продукт { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<int> Клиент { get; set; }
        public Nullable<int> Скидка { get; set; }
        public Nullable<int> Сотрудник { get; set; }
        public Nullable<int> Склад { get; set; }
    
        public virtual Акции Акции { get; set; }
        public virtual БазаКлиентов БазаКлиентов { get; set; }
        public virtual Продукт Продукт1 { get; set; }
        public virtual Объекты Объекты { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Операции> Операции { get; set; }
    }
}
