//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_store.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Операции
    {
        public int ID { get; set; }
        public string Название { get; set; }
        public Nullable<System.DateTime> Время { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public Nullable<int> Продукт { get; set; }
        public Nullable<int> Заказ { get; set; }
        public Nullable<int> Сотрудник { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Продукт Продукт1 { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
