//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_store.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукты
    {
        public int ID { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<int> Продукт { get; set; }
        public Nullable<int> Склад { get; set; }
    
        public virtual Объекты Объекты { get; set; }
        public virtual Продукт Продукт1 { get; set; }
    }
}
