//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_store.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники()
        {
            this.Заказы = new HashSet<Заказы>();
            this.Операции = new HashSet<Операции>();
        }
    
        public int ID { get; set; }
        public string ФИО { get; set; }
        public string Пол { get; set; }
        public System.DateTime ДатаРождения { get; set; }
        public string МестоЖительства { get; set; }
        public string Телефон { get; set; }
        public System.DateTime ДатаТрудоустройства { get; set; }
        public decimal Зарплата { get; set; }
        public int Объект { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public int Должность { get; set; }
        public byte[] Фото { get; set; }
    
        public virtual Должности Должности { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказы> Заказы { get; set; }
        public virtual Объекты Объекты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Операции> Операции { get; set; }
    }
}
